### ISSUE TITLE
JSON keys in visualization options are not wrapped in quotes

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/streamsx.visualization#124]
Syntax errors are generated, e.g. `Expected a string and instead saw xKey.`

**Comment by sriumcp** [comment]
Are these errors on the side of the code editor? Or in the browser console?

**Comment by queeniema** [comment]
Sorry, forgot to mention that. They appear on the side of the code editor.

**Comment by sriumcp** [comment]
Updated the code editor options (and also changed the editor theme while I was at it).

You might still get a warning, but the errors should disappear now.
