### ISSUE TITLE
Unable to start READ

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.visualization#125]
I am getting the following error when running meteor npm install:

chanskw:READ.develop chanskw$ meteor npm install
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/chanskw/.meteor/packages/meteor-tool/.1.4.2_1.19y1l9i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/chanskw/.meteor/packages/meteor-tool/1.4.2_1/mt-os.osx.x86_64/dev_bundle/bin/npm" "install"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babel-runtime@^6.18.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 6.11.6, 6.9.2, 6.9.1, 6.9.0, 6.6.1, 6.6.0, 6.5.0, 6.5.0-1, 6.3.19, 6.3.13, 6.2.4, 6.2.0, 6.1.18, 6.1.17, 6.1.4, 6.0.14, 6.0.12, 6.0.8, 6.0.2, 5.8.38, 5.8.35, 5.8.34, 5.8.29, 5.8.25, 5.8.24, 5.8.20, 5.8.19, 5.8.12, 5.8.9, 5.8.8, 5.8.5, 5.8.3, 5.8.2, 5.7.0, 5.6.20, 5.6.19, 5.6.18, 5.6.17, 5.6.16, 5.6.15, 5.6.14, 5.6.12, 5.6.11, 5.6.10, 5.6.9, 5.6.8, 5.6.7, 5.6.6, 5.6.5, 5.6.4, 5.6.3, 5.6.2, 5.6.1, 5.6.0, 5.5.8, 5.5.7, 5.5.6, 5.5.5, 5.5.4, 5.5.3, 5.5.2, 5.5.1, 5.5.0, 5.4.7, 5.4.6, 5.4.5, 5.4.4, 5.4.3, 5.4.2, 5.4.1, 5.4.0, 5.3.3, 5.3.2, 5.3.1, 5.3.0, 5.2.17, 5.2.16, 5.2.15, 5.2.14, 5.2.13, 5.2.12, 5.2.11, 5.2.10, 5.2.9, 5.2.7, 5.2.6, 5.2.5, 5.2.4, 5.2.3, 5.2.2, 5.2.1, 5.2.0, 5.1.13, 5.1.12, 5.1.11, 5.1.10, 5.1.9, 5.1.8, 5.1.7, 5.1.6, 5.1.5, 5.1.4, 5.1.3, 5.1.2, 5.1.1, 5.1.0, 5.0.13, 5.0.12, 5.0.11, 5.0.10, 5.0.9, 5.0.8, 5.0.7, 5.0.6, 5.0.5, 5.0.4, 5.0.3, 5.0.2, 5.0.1, 5.0.0, 5.0.0-beta4, 5.0.0-beta3, 5.0.0-beta2, 5.0.0-beta1, 4.7.16, 4.7.15, 4.7.14, 4.7.13, 4.7.12, 4.7.11, 4.7.10, 4.7.9, 4.7.8, 4.7.7, 4.7.6, 4.7.5, 4.7.4, 4.7.3, 4.7.2, 4.7.1, 4.7.0, 4.6.6, 4.6.5, 4.6.4, 4.6.3, 4.6.1, 4.6.0, 4.5.5, 4.5.4, 4.5.3, 4.5.2, 4.5.1, 4.5.0, 4.4.6, 4.4.5, 4.4.4, 4.4.3, 4.4.2, 4.4.1, 4.3.0, 4.2.1, 4.2.0, 4.1.1, 4.0.2, 4.0.1
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'READ.develop'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chanskw/git/streamsx.visualization/READ.develop/npm-debug.log

here's the log file:
0 info it worked if it ends with ok
1 verbose cli [ '/Users/chanskw/.meteor/packages/meteor-tool/.1.4.2_1.19y1l9i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
1 verbose cli   '/Users/chanskw/.meteor/packages/meteor-tool/1.4.2_1/mt-os.osx.x86_64/dev_bundle/bin/npm',
1 verbose cli   'install' ]
2 info using npm@3.10.9
3 info using node@v4.6.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree

**Comment by sriumcp** [comment]
Could you please try running `meteor update` within the READ.develop folder and after that try the `meteor npm install` command again?

**Comment by sriumcp** [comment]
Updated package versions for READ for compatibility with latest Meteor release. Please git clone the latest READ, and try `meteor npm install` within READ.develop.

**Comment by sriumcp** [comment]
Does the `meteor update` or does the latest READ release fix the issue with `meteor npm install`? If yes, I will close this issue.

**Comment by chanskw** [comment]
meteor update did not work.  I am going to pull the latest and try again.

**Comment by chanskw** [comment]
Cloned a new workspace and still get problem running meteor npm install:

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/chanskw/.meteor/packages/meteor-tool/.1.4.2_3.130d6md++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/chanskw/.meteor/packages/meteor-tool/1.4.2_3/mt-os.osx.x86_64/dev_bundle/bin/npm" "install"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babel-runtime@^6.18.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 6.11.6, 6.9.2, 6.9.1, 6.9.0, 6.6.1, 6.6.0, 6.5.0, 6.5.0-1, 6.3.19, 6.3.13, 6.2.4, 6.2.0, 6.1.18, 6.1.17, 6.1.4, 6.0.14, 6.0.12, 6.0.8, 6.0.2, 5.8.38, 5.8.35, 5.8.34, 5.8.29, 5.8.25, 5.8.24, 5.8.20, 5.8.19, 5.8.12, 5.8.9, 5.8.8, 5.8.5, 5.8.3, 5.8.2, 5.7.0, 5.6.20, 5.6.19, 5.6.18, 5.6.17, 5.6.16, 5.6.15, 5.6.14, 5.6.12, 5.6.11, 5.6.10, 5.6.9, 5.6.8, 5.6.7, 5.6.6, 5.6.5, 5.6.4, 5.6.3, 5.6.2, 5.6.1, 5.6.0, 5.5.8, 5.5.7, 5.5.6, 5.5.5, 5.5.4, 5.5.3, 5.5.2, 5.5.1, 5.5.0, 5.4.7, 5.4.6, 5.4.5, 5.4.4, 5.4.3, 5.4.2, 5.4.1, 5.4.0, 5.3.3, 5.3.2, 5.3.1, 5.3.0, 5.2.17, 5.2.16, 5.2.15, 5.2.14, 5.2.13, 5.2.12, 5.2.11, 5.2.10, 5.2.9, 5.2.7, 5.2.6, 5.2.5, 5.2.4, 5.2.3, 5.2.2, 5.2.1, 5.2.0, 5.1.13, 5.1.12, 5.1.11, 5.1.10, 5.1.9, 5.1.8, 5.1.7, 5.1.6, 5.1.5, 5.1.4, 5.1.3, 5.1.2, 5.1.1, 5.1.0, 5.0.13, 5.0.12, 5.0.11, 5.0.10, 5.0.9, 5.0.8, 5.0.7, 5.0.6, 5.0.5, 5.0.4, 5.0.3, 5.0.2, 5.0.1, 5.0.0, 5.0.0-beta4, 5.0.0-beta3, 5.0.0-beta2, 5.0.0-beta1, 4.7.16, 4.7.15, 4.7.14, 4.7.13, 4.7.12, 4.7.11, 4.7.10, 4.7.9, 4.7.8, 4.7.7, 4.7.6, 4.7.5, 4.7.4, 4.7.3, 4.7.2, 4.7.1, 4.7.0, 4.6.6, 4.6.5, 4.6.4, 4.6.3, 4.6.1, 4.6.0, 4.5.5, 4.5.4, 4.5.3, 4.5.2, 4.5.1, 4.5.0, 4.4.6, 4.4.5, 4.4.4, 4.4.3, 4.4.2, 4.4.1, 4.3.0, 4.2.1, 4.2.0, 4.1.1, 4.0.2, 4.0.1
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'READ.develop'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chanskw/git/streamsx.visualization/READ.develop/npm-debug.log

**Comment by chanskw** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/chanskw/.meteor/packages/meteor-tool/.1.4.2_3.130d6md++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
1 verbose cli   '/Users/chanskw/.meteor/packages/meteor-tool/1.4.2_3/mt-os.osx.x86_64/dev_bundle/bin/npm',
1 verbose cli   'install' ]
2 info using npm@3.10.9
3 info using node@v4.6.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree

**Comment by sriumcp** [comment]
Seems to be related to this issue: https://github.com/npm/npm/issues/4984 - with the solution being update of npm.

Are you doing `meteor npm install` or simply `npm install`?

**Comment by sriumcp** [comment]
Closing this issue since there seems to be no further comments on this thread.
