### ISSUE TITLE
Leaflet help

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.visualization#143]
I have few sample that use leaflet and I'm not able to create them using the toolkit.

Is anyone knows how to ? 

areas.html uses geofences.txt
cluster.html uses cluster.txt

[Sample.zip](https://github.com/IBMStreams/streamsx.visualization/files/634327/Sample.zip)

[data.zip](https://github.com/IBMStreams/streamsx.visualization/files/634362/data.zip)

This is one of the x transform function I tried on the dataset for areas

x =>{
        return {
        center: {
            lat: 55.618881,
            lng: 12.079211,
            zoom: 1
            
        },
        defaults: {
            scrollWheelZoom: false
            
        },
        geojson: {
            data:x.tuples[0].tuple,
            style: {
                fillColor: '#ccfa12',
                weight: 2,
                opacity: 1,
                color: 'white',
                dashArray: '3',
                fillOpacity: 0.7
            }
        }
    }
}

**Comment by sriumcp** [comment]
Could you please export your READ app -- make a gist out of it -- and give me a link to the gist? This will help me understand what your app is doing... You can export an app by going to the Apps tab and clicking on the up arrow in the sidebar -- which copies your READ app as a JSON object for others to import.

**Comment by jchailloux** [comment]
Here is the json file.

[MyApp.json.zip](https://github.com/IBMStreams/streamsx.visualization/files/636170/MyApp.json.zip)

**Comment by sriumcp** [comment]
I don't have the full picture since I don't have access to data produced by ws://localhost:56652 and ws://localhost:56651.

But after importing your app, one thing I noticed right away was that in your **Geofenses** dataset, you have a transform function that uses state (parent dataset = Raw; latest value from Raw = x; current state = s), but state is not enabled and initialized.

Could you please enable the state and set to some valid initial value (is s an array? If so, perhaps an empty array [] is a valid initial value in your situation)? This is briefly described in the **usage info** tab of the transform dataset.

**Comment by sriumcp** [comment]
I also noticed that you have Pie, Multibar Horizontal, and Leaflet Map visualizations defined for **Geofences** dataset. While Pie and Multibar Horizontal require the data to be an array, Leaflet Map requires the data to be an object. So, the three of them are not going to work on the same dataset. You can know more about the data formats by looking into the **usage info** for each visualization, and also by examining the sample app bundled with READ which includes a dataset for every supported READ visualization.

**Comment by jchailloux** [comment]
The leaflet map should use the GeoJSON dataset.

I sent yo the copy of the data part on the dataset page.

[geoJSON.dataset.zip](https://github.com/IBMStreams/streamsx.visualization/files/636990/geoJSON.dataset.zip)

**Comment by sriumcp** [comment]
When I paste your dataset into a raw dataset, I stuff like this: `"features": "{\"type\": \"FeatureCollection\",\"features\":` ... which is **invalid json**. Could you please verify / ensure that your READ dataset is producing valid json -- to start with, no escaped quotes.

**Comment by jchailloux** [comment]
JSON.parse(x.tuples[0].tuple.features) does the trick.

How can have the same capability such as changing the color according to the number of entities inside like I did in the areas.html ?
function getColor(d) {
	return d > 6000 ? '#800000' :
	       d > 5000 ? '#800026' :
	       d > 4000  ? '#BD0026' :
	       d > 3000  ? '#E31A1C' :
	       d > 2000  ? '#FC4E2A' :
	       d > 1000   ? '#FD8D3C' :
	       d > 500   ? '#FEB24C' :
	       d > 100   ? '#FED976' :
	                  '#FFEDA0';
}


What about a popup onmouseover ?



![image](https://cloud.githubusercontent.com/assets/7124757/20975387/a93fe2e0-bc9f-11e6-9604-6fbbe3e6afd9.png)

**Comment by sriumcp** [comment]
For styling... here is an idea. This assumes that you want to style each feature based on `feature.properties.number` -- if you want to use a different property, e.g., `feature.properties.density` modify this function appropriately (and also modify the properties object appropriately so that it contains the data you need for the style function).

Transform your geojson using the following logic...
```
/* x is the geojson */
x => {
  /* We are setting a style function for the geojson -- this is something angular-leaflet-directive understands */
    x.geojson.style = function style(feature) {
      /* We want to style each feature based on feature.properties.number */
        let d = feature.properties.number;
        return {
            /* set fillColor based on feature.properties.number */
            fillColor:  d > 6000 ? '#800000' :
                        d > 5000 ? '#800026' :
                        d > 4000 ? '#BD0026' :
                        d > 3000 ? '#E31A1C' :
                        d > 2000 ? '#FC4E2A' :
                        d > 1000 ? '#FD8D3C' :
                        d > 500 ? '#FEB24C' :
                        d > 100 ? '#FED976' :
                        '#FFEDA0',
            weight: 2,
            opacity: 1,
            color: 'white',
            dashArray: '3',
            fillOpacity: 0.7
        }
    };
    return x;
}
```

**Comment by jchailloux** [comment]
I miss the point.
In the same transform or do I have to transform again x from the previous transform ?

**Comment by sriumcp** [comment]
Either way is fine... ultimately, we want the data used by the visualization to contain the style callback. So you can do it in the same function or in a new function.

**Comment by jchailloux** [comment]
Great

this works
x =>{
        return {
        center: {
            lat: 55.618881,
            lng: 12.079211,
            zoom: 14
            
        },
        defaults: {
            scrollWheelZoom: false
            
        },
        geojson: {
            data:JSON.parse(x.tuples[0].tuple.features),
            style: function style(feature) {
      /* We want to style each feature based on feature.properties.number */
        let d = feature.properties.number;
        return {
            /* set fillColor based on feature.properties.number */
            fillColor:  d > 6 ? '#800000' :
                        d > 5 ? '#800026' :
                        d > 4 ? '#BD0026' :
                        d > 3 ? '#E31A1C' :
                        d > 2 ? '#FC4E2A' :
                        d > 1 ? '#FD8D3C' :
                        d > 500 ? '#FEB24C' :
                        d > 100 ? '#FED976' :
                        '#FFEDA0',
            weight: 2,
            opacity: 1,
            color: 'white',
            dashArray: '3',
            fillOpacity: 0.7
        }
    }
        }
    }
}

**Comment by sriumcp** [comment]
Perfect. Just out of curiosity... can you show me your new map also?

**Comment by jchailloux** [comment]
What about the mouse over could we have this function available to update ?
Could we display the legend for colors ?

![image](https://cloud.githubusercontent.com/assets/7124757/20976814/0229a5a4-bca4-11e6-8196-96979d5ecd32.png)

**Comment by sriumcp** [comment]
legends are already supported... please look into the maps dashboard that is part of the sample app (included when you download READ).

**Comment by sriumcp** [comment]
For binding a popup on mouseover... could you please experiment with the onEachFeature callback as I mentioned here. Leaflet documentation is here:  http://leafletjs.com/reference.html#geojson (again I'm not 100% certain this solution works since I'm yet to test this).

**Comment by jchailloux** [comment]
In the areas.html I did that.
The question is more about where to write the code I want.

function style(feature) {
	return {
		weight: 1,
		opacity: 1,
		color: 'white',
		dashArray: '1',
		fillOpacity: feature.properties.density+0.5,
//		fillOpacity: 0.6,
		fillColor: getColor(feature.properties.number)
	};
}

function highlightFeature(e) {
	var layer = e.target;

	layer.setStyle({
		weight: 1,
		color: '#000',
		dashArray: '',
		fillOpacity: 0.9
	});

	if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
		layer.bringToFront();
	}

	info.update(layer.feature.properties);
}

function resetHighlight(e) {
	geojsonLayer.resetStyle(e.target);
	info.update();
}

function zoomToFeature(e) {
	map.fitBounds(e.target.getBounds());
}

function onEachFeature(feature, layer) {
	layer.on({
		mouseover: highlightFeature,
		mouseout: resetHighlight,
		click: zoomToFeature
	});
}

var geojsonLayer;
var legend = L.control({position: 'bottomright'});

**Comment by sriumcp** [comment]
onEachFeature would be a assigned to geojson just like style... geojson will now have data, style, **and** onEachFeature, with the last two being functions.

**Comment by sriumcp** [comment]
Again, you can try this in the same transform where you are adding the style function.

**Comment by jchailloux** [comment]
onEachFeature looks with this code

x =>{
        return {
        center: {
            lat: 55.618881,
            lng: 12.079211,
            zoom: 14
            
        },
        defaults: {
            scrollWheelZoom: false
            
        },
        geojson: {
            data:JSON.parse(x.tuples[0].tuple.features),
            style: function style(feature) {
                /* We want to style each feature based on feature.properties.number */
                let d = feature.properties.number;
                return {
                    /* set fillColor based on feature.properties.number */
                    fillColor:  d > 6 ? '#800000' :
                                d > 5 ? '#800026' :
                                d > 4 ? '#BD0026' :
                                d > 3 ? '#E31A1C' :
                                d > 2 ? '#FC4E2A' :
                                d > 1 ? '#FD8D3C' :
                                d > 500 ? '#FEB24C' :
                            d > 100 ? '#FED976' :
                            '#FFEDA0',
                    weight: 2,
                    opacity: 1,
                    color: 'white',
                    dashArray: '3',
                    fillOpacity: 0.7
                }
            },
            onEachFeature: function onEachFeature(feature, layer) {
            	layer.on({
            		mouseover: function highlightFeature(e) {
                        	var layer = e.target;
                        
                        	layer.setStyle({
                        		weight: 1,
                        		color: '#000',
                        		dashArray: '',
                        		fillOpacity: 0.9
                        	});
                        
                        	if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
                        		layer.bringToFront();
                        	}
                        
                        	info.update(layer.feature.properties);
                        }
,
            		mouseout: function resetHighlight(e) {
                            	geojsonLayer.resetStyle(e.target);
                            	info.update();
                            }
                            ,
            		click: function zoomToFeature(e) {
                        	map.fitBounds(e.target.getBounds());
                        }
            	});
            }
}
    }
}





        return {
        center: {
            lat: 55.618881,
            lng: 12.079211,
            zoom: 14
            
        },
        defaults: {
            scrollWheelZoom: false
            
        },
        geojson: {
            data:JSON.parse(x.tuples[0].tuple.features),
            style: function style(feature) {
                /* We want to style each feature based on feature.properties.number */
                let d = feature.properties.number;
                return {
                    /* set fillColor based on feature.properties.number */
                    fillColor:  d > 6 ? '#800000' :
                                d > 5 ? '#800026' :
                                d > 4 ? '#BD0026' :
                                d > 3 ? '#E31A1C' :
                                d > 2 ? '#FC4E2A' :
                                d > 1 ? '#FD8D3C' :
                                d > 500 ? '#FEB24C' :
                            d > 100 ? '#FED976' :
                            '#FFEDA0',
                    weight: 2,
                    opacity: 1,
                    color: 'white',
                    dashArray: '3',
                    fillOpacity: 0.7
                }
            },
            onEachFeature: function onEachFeature(feature, layer) {
            	layer.on({
            		mouseover: function highlightFeature(e) {
                        	var layer = e.target;
                        
                        	layer.setStyle({
                        		weight: 1,
                        		color: '#000',
                        		dashArray: '',
                        		fillOpacity: 0.9
                        	});
                        
                        	if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
                        		layer.bringToFront();
                        	}
                        
                        	info.update(layer.feature.properties);
                        }
,
            		mouseout: function resetHighlight(e) {
                            	geojsonLayer.resetStyle(e.target);
                            	info.update();
                            }
                            ,
            		click: function zoomToFeature(e) {
                        	map.fitBounds(e.target.getBounds());
                        }
            	});
            }
}
    }
}

![image](https://cloud.githubusercontent.com/assets/7124757/20978276/8ed5db54-bca8-11e6-88b8-c0a37c0cb506.png)

**Comment by jchailloux** [comment]
The info is not display.
Do you have an other great idea ?

var info = L.control();

info.onAdd = function (map) {
	this._div = L.DomUtil.create('div', 'info');
	this.update();
	return this._div;
};

info.update = function (props) {
	this._div.innerHTML = '<h4>Areas Density</h4>' +  (props ?
		'<i>'+new Date(props.ts).toGMTString()+'</i><br/>'+'<b>' + props.name + '('+ props.OBJECTID+') : '+parseInt( props.area ).toLocaleString()+' m<sup>2</sup></b><br />' + props.number + ' people<br />' + props.density.toLocaleString(undefined, { minimumFractionDigits: 4 }) + ' people / m<sup>2</sup>'
		: ' over a zones');
};
info.addTo(map);

**Comment by jchailloux** [comment]
For legend I have some issues

![image](https://cloud.githubusercontent.com/assets/7124757/20978745/534897dc-bcaa-11e6-8665-12cf1013d4d8.png)

**Comment by jchailloux** [comment]
I also notice that the mouseout and click don't work.

**Comment by sriumcp** [comment]
I see... Please try importing this new sample app: https://gist.github.com/sriumcp/9b9ecc058b1e9b3f505d7bbf335b4cf5

I will fix the app bundled with READ soon.

**Comment by sriumcp** [comment]
<img width="1420" alt="screen shot 2016-12-07 at 12 32 38 pm" src="https://cloud.githubusercontent.com/assets/5309125/20979080/5560b2e2-bc79-11e6-8211-057a84ce33de.png">

**Comment by jchailloux** [comment]
Legend is ok now thanks

![image](https://cloud.githubusercontent.com/assets/7124757/20979390/0d81f646-bcad-11e6-8711-6f13807b41c8.png)

**Comment by jchailloux** [comment]
Could we avoid to set 
   center: {
            lat: 55.618881,
            lng: 12.079211,
            zoom: 14
            
        },

at all time and then let the user zomm in or out and move ?
At all time it goes back to the "default"

**Comment by sriumcp** [comment]
Two ideas.

1. Move the center object within the defaults object (instead of keeping them at the same level; this will create an initial centering with user control for zooming)
2. Remove the center object altogether (there will no initial centering)

**Comment by sriumcp** [comment]
Could you please export your current READ app and give me a link... I can try experimenting with mouseover and mouseout and click.

**Comment by jchailloux** [comment]
[Demo_READ.json.zip](https://github.com/IBMStreams/streamsx.visualization/files/637341/Demo_READ.json.zip)
I sent you the streams application on email

**Comment by jchailloux** [comment]
[StreamsUI.zip](https://github.com/IBMStreams/streamsx.visualization/files/637351/StreamsUI.zip)
This is the node application I would like to move on the toolkit (in case of)

**Comment by sriumcp** [comment]
Could you please replace your onEachFeature function with the below function? This is the angular leaflet way of manipulating the map object (sorry -- its not yet fully documented in READ; I'm planning to switch from angular-leaflet to the direct leaflet library in the next release to make map making in READ simpler)... 

```
            onEachFeature: function onEachFeature(feature, layer) {
            	layer.on({
            		mouseover: function highlightFeature(e) {
                        	var layer = e.target;
                        
                        	layer.setStyle({
                        		weight: 1,
                        		color: '#000',
                        		dashArray: '',
                        		fillOpacity: 0.9
                        	});
                        
                        	if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
                        		layer.bringToFront();
                        	}
                        },
                    mouseout: function mouseOut(e) {
                            leafletData.getGeoJSON().then(geojson => {
                        	    geojson.resetStyle(e.target);
                        	})                        
                    },
            		click: function zoomToFeature(e) {
                            leafletData.getMap().then(map => {
                        	    map.fitBounds(e.target.getBounds());
                        	});
                        }
            	});
            }
```

**Comment by jchailloux** [comment]
This solved the mouse issues.
The pending issues are info not display on mouseover and removed on mouseout and zoom/center always reset.

Don't be sorry READ looks so promises.

**Comment by sriumcp** [comment]
Re: the zoom/center, did you move the center into the defaults property, or is it still at the top level?
```        defaults: {
            scrollWheelZoom: false,
            center: {
                lat: 55.618881,
                lng: 12.079211,
                zoom: 14
                
            },
        },
```

**Comment by jchailloux** [comment]
still in the x transform

**Comment by jchailloux** [comment]
switching to default solve the issue
thanks

**Comment by sriumcp** [comment]
How about this function? Of course, you will need to change the popup content and latlng based on feature properties... 

```
            onEachFeature: function onEachFeature(feature, layer) {
            	layer.on({
            		mouseover: function highlightFeature(e) {
                        	var layer = e.target;
                        
                        	layer.setStyle({
                        		weight: 1,
                        		color: '#000',
                        		dashArray: '',
                        		fillOpacity: 0.9
                        	});
                        
                        	if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
                        		layer.bringToFront();
                        	}

                            leafletData.getMap().then(map => {
                                var popup = L.popup()
                                .setContent('<p>Hello world!<br />This is a nice popup.</p>')
                                .setLatLng(L.latLng(55.618881, 12.079211))
                                .openOn(map);                        	
                        	});
                        	

                        	
                        },
                    mouseout: function mouseOut(e) {
                            leafletData.getGeoJSON().then(geojson => {
                        	    geojson.resetStyle(e.target);
                        	});
                            leafletData.getMap().then(map => {
                                console.log(map);
                                map.closePopup();
                        	});

                    },
            		click: function zoomToFeature(e) {
                            leafletData.getMap().then(map => {
                        	    map.fitBounds(e.target.getBounds());
                        	});
                        }
            	});
            }
```

**Comment by jchailloux** [comment]
I updated the popup as follow.
I have some issues (some blink popup) but I guess it's because I have fences inside fences.

                                        leafletData.getMap().then(map => {
                                            var popup = L.popup()
                                            .setContent('<h4>Areas Density</h4>'+'<i>'+new Date(feature.properties.ts).toGMTString()+'</i><br/>'+'<b>' + feature.properties.name + '('+ feature.properties.OBJECTID+') : '+parseInt( feature.properties.area ).toLocaleString()+' m<sup>2</sup></b><br/>' + feature.properties.number + ' people<br />' + feature.properties.density.toLocaleString(undefined, { minimumFractionDigits: 4 }) + ' people / m<sup>2</sup>' )
                                            .setLatLng(L.latLng(feature.geometry.coordinates[0][0][1], feature.geometry.coordinates[0][0][0]))
                                            .openOn(map);                        	
                                    	});

thanks

**Comment by jchailloux** [comment]
could I get the upper right latlon to have the popup at the same place ?

**Comment by jchailloux** [comment]
[Demo_READ.json.zip](https://github.com/IBMStreams/streamsx.visualization/files/637771/Demo_READ.json.zip)

The last READ app

**Comment by sriumcp** [comment]
Yes, I notice the flickering as well. Could you try L.control instead of pop up -- now that you know how to get a reference to the map object? Going back to your original idea (of adding an info div) instead of a popup might resolve this issue.

**Comment by jchailloux** [comment]
I'm trying to migrate the Cluster.html on visualization.
I'm having issues because it looks like the marker definition is not valid.


using this transform
x => {
/*    taipei: {
                        layer: "northTaiwan",
                        lat: 25.0391667,
                        lng: 121.525,
                    }
*/        var markers='{';
        var first=1;
        	for (var value of x.tuples[0].tuple.locations) {
        		markers = markers+(first == 0?',':'')+value.id+':{lat:'+value.latitude+',lng:' +value.longitude+'}';
        		first=0;
        	}
            markers = markers+'}';
//  var markers = leafletData.getMap().markerClusterGroup();
  //	L.markers.clearLayers();
    return{
        defaults: {
            scrollWheelZoom: false,
             center: {
                        lat: 55.618881,
                        lng: 12.079211,
                        zoom: 14
                        
                    }
        },
        markers

    }
}

This is the output
{
  "defaults": {
    "scrollWheelZoom": false,
    "center": {
      "lat": 55.618881,
      "lng": 12.079211,
      "zoom": 14
    }
  },
  "markers": "{142:{lat:55.61476346106971,lng:12.06946614470684},14:{lat:55.615240079731045,lng:12.08811528552074},161:{lat:55.61174290104943,lng:12.077519594403434},20:{lat:55.62208372595761,lng:12.097116836162703},146:{lat:55.62137107740439,lng:12.08397103090601},134:{lat:55.621323562892904,lng:12.077009278061105},196:{lat:55.62424874263861,lng:12.090774580333495},166:{lat:55.61450581129024,lng:12.075062586655413},24:{lat:55.61044152035306,lng:12.092445946702231},3:{lat:55.61921674935665,lng:12.096485266871463}}"
}


[Demo_READ.json.zip](https://github.com/IBMStreams/streamsx.visualization/files/639175/Demo_READ.json.zip)

**Comment by jchailloux** [comment]
I tried this without success
                                        leafletData.getMap().then(map => {
                                            var info = L.control({position: 'bottomleft'});
                                            var _div = L.DomUtil.create('div', 'info');
                                            _div.innerHTML = '<h4>Areas Density</h4>'+'<i>'+new Date(feature.properties.ts).toGMTString()+'</i><br/>'+'<b>' + feature.properties.name + '('+ feature.properties.OBJECTID+') : '+parseInt( feature.properties.area ).toLocaleString()+' m<sup>2</sup></b><br/>' + feature.properties.number + ' people<br />' + feature.properties.density.toLocaleString(undefined, { minimumFractionDigits: 4 }) + ' people / m<sup>2</sup>';
                                           info.addTo(map);                        	
                                    	});

**Comment by sriumcp** [comment]
Ok... two points:

1. The markers object is not an object at all but is a string... markers are supported with proper objects not strings. Also, I am not sure if within marker objects the property keys could be numbers (I know strings work for sure).

2. When you share your READ app next time -- could you please replace the ws://... (Websocket) datasets with Raw datasets with the appropriate JSON data pasted in them? I know this kills all the dynamics and makes the app static -- but this is useful for sharing and debugging (I am not set up to run your Streams app properly; this makes it easier to debug the READ app).

**Comment by jchailloux** [comment]
[Demo_READ.json.zip](https://github.com/IBMStreams/streamsx.visualization/files/639454/Demo_READ.json.zip)

This should contains raw dataset for the RawClusterStack

**Comment by sriumcp** [comment]
With the following transform function for ClusterStackTrans...
```
x => {
	var markerObject = {};
	x.tuples[0].tuple.locations.map(y => {
	    markerObject[y.id] = {
	        lat: y.latitude,
	        lng: y.longitude,
	        message: "this place is on earth",
	        group: "Europe"
	    };
	});
	

    return{
        defaults: {
            scrollWheelZoom: false,
             center: {
                        lat: 55.618881,
                        lng: 12.079211,
                        zoom: 14
                        
                    }
        },
        markers: markerObject

    }
}
```

This map is the result.... 

<img width="1059" alt="screen shot 2016-12-08 at 8 16 13 am" src="https://cloud.githubusercontent.com/assets/5309125/21011299/a1073c84-bd1e-11e6-98a4-1c39801e7d1b.png">

I need to update and commit a new version of READ in order to support marker clustering (essentially include this leaflet plugin as a READ dependency). I can let you know once I have this up (you can upgrade to the latest version of READ once I do this).

**Comment by jchailloux** [comment]
[Demo_READ.json.zip](https://github.com/IBMStreams/streamsx.visualization/files/639497/Demo_READ.json.zip)

I did the same for the GeoJSONRaw regarding the popup and div info

**Comment by jchailloux** [comment]
For the Cluster I have MarkerCluster plugin not loaded

**Comment by sriumcp** [comment]
Yes, I am aware of the MarkerCluster plugin issue... fix is on the way!

**Comment by jchailloux** [comment]
When it will work it could be nice to create a "migration" guide base on the 2 samples.
I will work on and let you know to improve the doc ans samples.

**Comment by sriumcp** [comment]
Marker clusters are now supported in the latest version of READ (0.7.1)... 

Here's the updated transform function.
```
x => {
	var markerObject = {};
	x.tuples[0].tuple.locations.map(y => {
	    markerObject[y.id] = {
	        lat: y.latitude,
	        lng: y.longitude,
	        group: "Europe"
	    };
	});
	

    return {
        defaults: {
            scrollWheelZoom: false,
             center: {
                        lat: 55.618881,
                        lng: 12.079211,
                        zoom: 14
                        
                    }
        },
        markers: markerObject
    }
}
```

Notice that there is only a single change -- a new group property which got added to the markers (you can set the group as anything you want in this example).

Here's the result... 

<img width="1061" alt="screen shot 2016-12-08 at 12 40 02 pm" src="https://cloud.githubusercontent.com/assets/5309125/21020750/a5517186-bd43-11e6-85d0-05f995676dbe.png">

I will provide a quick list of steps for migration here (if you wish to help improve the documentation by creating a wiki page which properly documents these steps, you are very welcome to do so. Please issue a PR for the same).

**Comment by sriumcp** [comment]
## Migrating to READ version 0.7.1
1. Export your READ app and save it - for e.g., by creating a gist like [this one](https://gist.github.com/sriumcp/9b9ecc058b1e9b3f505d7bbf335b4cf5).
2. Stop your READ service(s)
3. `cd streamsx.visualization`
4. `git pull origin master`
5. `cd READ.develop`
6. `rm -rf node_modules`
7. `meteor npm install`
8. `meteor`
9. If you are running the **READ.share** service, do steps 6 and 7 within the `READ.share` folder as well.

**Comment by jchailloux** [comment]
I can see dataset but the visualization is blank

**Comment by sriumcp** [comment]
Yes, I see this issue too !! Let me fix this update a bit more...

**Comment by jchailloux** [comment]
I thought I made a mistake so I re-install from scratch without success.
I will migrate again when fixed.
thanks

**Comment by sriumcp** [comment]
This is due to breaking changes in angular: https://github.com/angular/angular.js/blob/master/CHANGELOG.md

I believe I know what to do... will update a shortly with a fix.

**Comment by sriumcp** [comment]
Could you please retry now... as you did earlier, please try to reinstall READ from scratch and import the app.

**Comment by jchailloux** [comment]
rm -fr streamsx.visualization/
git clone https://github.com/IBMStreams/streamsx.visualization.git
cd streamsx.visualization/READ.develop/
meteor npm install
meteor

**Comment by jchailloux** [comment]
is this correct ?

**Comment by sriumcp** [comment]
Yes, but this will delete your existing app. Hopefully, you have backed up the app after exporting it so that you can reimport.

**Comment by jchailloux** [comment]
Visualization is back
The cluster visualization works for few seconds and then no more plots

**Comment by jchailloux** [comment]
switching back to dataset and then visualization bring back plots but it stops after few sec again.
Do we have to clear the layer 	markers.clearLayers();

**Comment by jchailloux** [comment]
[out-3.ogv.zip](https://github.com/IBMStreams/streamsx.visualization/files/640503/out-3.ogv.zip)

This shows the result

**Comment by sriumcp** [comment]
Could you please slow down the updates to the marker and see what happens? Maybe the leaflet marker clustering plugin is not able to keep up?

**Comment by sriumcp** [comment]
What happens if you don't have a group (i.e., no clustering)?

**Comment by jchailloux** [comment]
I will reduce the speed and let you know .For real live purpose we have to find a solution.

**Comment by jchailloux** [comment]
What do you think about the clearLayers() ?

**Comment by sriumcp** [comment]
Please feel free to experiment with clearLayers.. I am not 100% sure what this API does (also READ is using Leaflet 0.7.x version and not the latest Leaflet 1.x.y version for various compatibility purposes... FYI).

**Comment by jchailloux** [comment]
I switch from 1 sec to 10 sec
The result is the same but it takes more time

**Comment by jchailloux** [comment]
It looks like it's not able to deal with the same id at different places over time.

**Comment by jchailloux** [comment]
how to clear layers ?

**Comment by sriumcp** [comment]
FYI... the next release of READ (something which I plan to release this month) will have direct access to the leaflet APIs (instead of having to go through angular-leaflet-directive, which doesn't really expose these methods as I would like)... I believe you should be able to call something like `markers.refreshClusters` which is a markerCluster method -- which is really what you are looking for.

In the meantime, I am afraid your main option is to look into how other users of angular-leaflet-directive have accomplished this cluster refresh (with leaflet v0.7.x).

On the whole, yes, I believe this is a refreshClusters / clear layers style issue.

**Comment by sriumcp** [comment]
Could you please try removing clustering (i.e., the `group` keyword) and try again.

**Comment by jchailloux** [comment]
I'm not loosing plots but I don't have the clustering capability. It looks like issue is at he cluster level for refresh (group)

**Comment by jchailloux** [comment]
group: Date.now().toLocaleString()

It looks like it does the trick. I will investigate more on that

**Comment by jchailloux** [comment]
Will I have a memory leak with so many groups ?

**Comment by jchailloux** [comment]
I confirm that the issue is that the group must change to have it running ok.
Could we remove groups and add new ?
The refresh will come soon as you said

**Comment by sriumcp** [comment]
Ok that's a good find. Yes, you can change the group id every time you get updated markers (and my guess is this is calling refreshGroups internally).

**Comment by jchailloux** [comment]
I will stay with that for now and waiting for your updates.
Let me know on GitHub and email.
Any ideas regarding heatmap ?
Thanks.

**Comment by sriumcp** [comment]
Can you provide an example for the type of heat map you're referring to?

**Comment by jchailloux** [comment]
something like this : http://leaflet.github.io/Leaflet.heat/demo/

**Comment by sriumcp** [comment]
Ok... I believe you can do this right now.

Could you please follow this documentation: https://github.com/tombatossals/angular-leaflet-directive/blob/master/doc/layers-attribute.md

And try creating a layers object (as part of your overall leaflet object which has defaults, markers, etc.)? You are simply creating a heat map layer -- that's it.
