### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.visualization#154]
I'm not able to start meteor with the last version

[jchailloux@jchaillouxserver streamsx.visualization]$ cd READ.develop/
[jchailloux@jchaillouxserver READ.develop]$ meteor
[[[[[ ~/streamsx.visualization/READ.develop ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
                                              
Unable to resolve some modules:

  "ace/lib/es5-shim" in                       
/home/jchailloux/streamsx.visualization/READ.develop/streamsx.visualization/READ.develop/public/bower_components/ace-builds/src-noconflict/worker-xquery.js
(web.browser)
  "markdown-it" in                            
/home/jchailloux/streamsx.visualization/READ.develop/streamsx.visualization/READ.develop/public/bower_components/bootstrap/grunt/bs-lessdoc-parser.js
(web.browser)
  "btoa" in                                   
/home/jchailloux/streamsx.visualization/READ.develop/streamsx.visualization/READ.develop/public/bower_components/bootstrap/grunt/bs-raw-files-generator.js
(web.browser)
  "shelljs" in                                
/home/jchailloux/streamsx.visualization/READ.develop/streamsx.visualization/READ.develop/public/bower_components/bootstrap/grunt/change-version.js
(web.browser)
  "jshint" in                                 
/home/jchailloux/streamsx.visualization/READ.develop/streamsx.visualization/READ.develop/public/bower_components/leaflet.markercluster/build/build.js
(web.browser)
  "karma" in                                  
/home/jchailloux/streamsx.visualization/READ.develop/streamsx.visualization/READ.develop/public/bower_components/leaflet.markercluster/build/build.js
(web.browser)
  "load-grunt-tasks" in                       
/home/jchailloux/streamsx.visualization/READ.develop/streamsx.visualization/READ.develop/public/bower_components/bootstrap/Gruntfile.js
(web.browser)
  "time-grunt" in                             
/home/jchailloux/streamsx.visualization/READ.develop/streamsx.visualization/READ.develop/public/bower_components/bootstrap/Gruntfile.js
(web.browser)
  "git-rev" in                                
/home/jchailloux/streamsx.visualization/READ.develop/streamsx.visualization/READ.develop/public/bower_components/leaflet/Jakefile.js
(web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save ace markdown-it btoa shelljs jshint karma load-grunt-tasks time-grunt git-rev
                                              
   Processing files with fourseven:scss ...  |
<--- Last few GCs --->

  107112 ms: Mark-sweep 1395.7 (1456.3) -> 1395.7 (1456.3) MB, 690.5 / 0 ms [allocation failure] [GC in old space requested].
  107801 ms: Mark-sweep 1395.7 (1456.3) -> 1395.7 (1456.3) MB, 689.8 / 0 ms [allocation failure] [GC in old space requested].
  108497 ms: Mark-sweep 1395.7 (1456.3) -> 1395.7 (1456.3) MB, 695.1 / 0 ms [last resort gc].
  109188 ms: Mark-sweep 1395.7 (1456.3) -> 1395.7 (1456.3) MB, 691.5 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3737294b4629 <JS Object>
    1: addMappingWithCode(aka addMappingWithCode) [/home/jchailloux/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-node.js:~144] [pc=0x186c18f308be] (this=0x3737294041b9 <undefined>,mapping=0x3b2d992c8ae1 <an Object with map 0x3eeec786fd1>,code=0x2c831316c669 <String[4]: ] = >)
    2: /*...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)
--------------------------------------------------------------------------------[jchailloux@jchaillouxserver READ.develop]$ meteor npm install

> READ.develop@0.7.1 postinstall /home/jchailloux/streamsx.visualization/READ.develop
> node_modules/bower/bin/bower install --allow-root

bower                     invalid-meta for:/home/jchailloux/streamsx.visualization/READ.develop/bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower leaflet.markercluster extra-resolution Unnecessary resolution: leaflet.markercluster#leaflet-0.7

--------------------------------------------------------------------------------
[jchailloux@jchaillouxserver READ.develop]$ meteor npm install --save ace markdown-it btoa shelljs jshint karma load-grunt-tasks time-grunt git-rev
npm WARN deprecated node-uuid@1.4.3: use uuid module instead
npm WARN prefer global jshint@2.9.4 should be installed with -g
READ.develop@0.7.1 /home/jchailloux/streamsx.visualization/READ.develop
├─┬ ace@1.3.0 
│ ├── archy@1.0.0 
│ ├─┬ async-retry@0.1.1 
│ │ ├─┬ babel-runtime@6.5.0 
│ │ │ └── core-js@1.2.7 
│ │ └── retry@0.9.0 
│ ├── babel-runtime@6.6.1 
│ ├── easy-table@1.0.0 
│ ├─┬ es6-promisify@4.0.0 
│ │ └── es6-promise@3.3.1 
│ ├─┬ fs-promise@0.5.0 
│ │ ├── any-promise@1.3.0 
│ │ ├── fs-extra@0.26.7 
│ │ ├── mz@2.6.0 
│ │ └─┬ thenify-all@1.6.0 
│ │   └── thenify@3.2.1 
│ ├─┬ got@5.3.1 
│ │ ├─┬ create-error-class@2.0.1 
│ │ │ └── capture-stack-trace@1.0.0 
│ │ ├─┬ duplexer2@0.1.4 
│ │ │ └─┬ readable-stream@2.2.2 
│ │ │   └── isarray@1.0.0 
│ │ ├── is-plain-obj@1.1.0 
│ │ ├── is-redirect@1.0.0 
│ │ ├── lowercase-keys@1.0.0 
│ │ ├── node-status-codes@1.0.0 
│ │ ├── object-assign@4.1.0 
│ │ ├─┬ parse-json@2.2.0 
│ │ │ └─┬ error-ex@1.3.0 
│ │ │   └── is-arrayish@0.2.1 
│ │ ├─┬ read-all-stream@3.1.0 
│ │ │ └─┬ readable-stream@2.2.2 
│ │ │   └── isarray@1.0.0 
│ │ ├─┬ readable-stream@2.2.2 
│ │ │ └── isarray@1.0.0 
│ │ ├── timed-out@2.0.0 
│ │ ├── unzip-response@1.0.2 
│ │ └─┬ url-parse-lax@1.0.0 
│ │   └── prepend-http@1.0.4 
│ ├─┬ gunzip-maybe@1.2.1 
│ │ ├─┬ browserify-zlib@0.1.4 
│ │ │ └── pako@0.2.9 
│ │ ├─┬ peek-stream@1.1.1 
│ │ │ └─┬ through2@0.5.1 
│ │ │   └── xtend@3.0.0 
│ │ ├── pumpify@1.3.5 
│ │ └─┬ through2@0.4.2 
│ │   └─┬ xtend@2.1.2 
│ │     └── object-keys@0.4.0 
│ ├─┬ https-proxy-agent@1.0.0 
│ │ └─┬ agent-base@2.0.1 
│ │   └── semver@5.0.3 
│ ├─┬ init-package-json@1.9.1 
│ │ ├── glob@5.0.15 
│ │ ├── promzard@0.3.0 
│ │ ├─┬ read@1.0.7 
│ │ │ └── mute-stream@0.0.6 
│ │ ├─┬ read-package-json@2.0.4 
│ │ │ ├── glob@6.0.4 
│ │ │ ├─┬ json-parse-helpfulerror@1.0.3 
│ │ │ │ └── jju@1.3.0 
│ │ │ └─┬ normalize-package-data@2.3.5 
│ │ │   └─┬ is-builtin-module@1.0.0 
│ │ │     └── builtin-modules@1.1.1 
│ │ ├─┬ validate-npm-package-license@3.0.1 
│ │ │ ├─┬ spdx-correct@1.0.2 
│ │ │ │ └── spdx-license-ids@1.2.2 
│ │ │ └── spdx-expression-parse@1.0.4 
│ │ └─┬ validate-npm-package-name@2.2.2 
│ │   └── builtins@0.0.7 
│ ├─┬ mkdirp-then@1.2.0 
│ │ └─┬ mkdirp@0.5.1 
│ │   └── minimist@0.0.8 
│ ├── node-uuid@1.4.3 
│ ├─┬ npm-package-arg@4.1.0 
│ │ └── hosted-git-info@2.1.5 
│ ├─┬ readdir-scoped-modules@1.0.2 
│ │ ├── debuglog@1.0.1 
│ │ └─┬ dezalgo@1.0.3 
│ │   └── asap@2.0.5 
│ ├── semver@5.0.1 
│ └─┬ tar@2.2.1 
│   ├── block-stream@0.0.9 
│   └── fstream@1.0.10 
├── btoa@1.1.2 
├── git-rev@0.2.1 
├── UNMET PEER DEPENDENCY grunt@>=0.4.0
├─┬ jshint@2.9.4 
│ ├── cli@1.0.1 
│ ├─┬ console-browserify@1.1.0 
│ │ └── date-now@0.1.4 
│ ├── exit@0.1.2 
│ ├─┬ htmlparser2@3.8.3 
│ │ ├── entities@1.0.0 
│ │ └── readable-stream@1.1.14 
│ ├── lodash@3.7.0 
│ ├── shelljs@0.3.0 
│ └── strip-json-comments@1.0.4 
├─┬ karma@1.3.0 
│ ├── bluebird@3.4.6 
│ ├─┬ chokidar@1.6.1 
│ │ ├── anymatch@1.3.0 
│ │ ├── async-each@1.0.1 
│ │ ├── glob-parent@2.0.0 
│ │ ├─┬ is-binary-path@1.0.1 
│ │ │ └── binary-extensions@1.8.0 
│ │ ├─┬ is-glob@2.0.1 
│ │ │ └── is-extglob@1.0.0 
│ │ └─┬ readdirp@2.1.0 
│ │   ├─┬ readable-stream@2.2.2 
│ │   │ └── isarray@1.0.0 
│ │   └── set-immediate-shim@1.0.1 
│ ├── colors@1.1.2 
│ ├── combine-lists@1.0.1 
│ ├── connect@3.5.0 
│ ├── di@0.0.1 
│ ├─┬ dom-serialize@2.2.1 
│ │ ├── custom-event@1.0.1 
│ │ ├── ent@2.2.0 
│ │ └── void-elements@2.0.1 
│ ├─┬ expand-braces@0.1.2 
│ │ ├── array-slice@0.2.3 
│ │ └─┬ braces@0.1.5 
│ │   └─┬ expand-range@0.1.1 
│ │     ├── is-number@0.1.1 
│ │     └── repeat-string@0.2.2 
│ ├─┬ http-proxy@1.16.2 
│ │ └── requires-port@1.0.0 
│ ├── isbinaryfile@3.0.1 
│ ├── lodash@3.10.1 
│ ├─┬ log4js@0.6.38 
│ │ └── semver@4.3.6 
│ ├── qjobs@1.1.5 
│ ├─┬ socket.io@1.4.7 
│ │ ├─┬ engine.io@1.6.10 
│ │ │ ├─┬ accepts@1.1.4 
│ │ │ │ ├─┬ mime-types@2.0.14 
│ │ │ │ │ └── mime-db@1.12.0 
│ │ │ │ └── negotiator@0.4.9 
│ │ │ ├── base64id@0.1.0 
│ │ │ ├─┬ engine.io-parser@1.2.4 
│ │ │ │ ├── base64-arraybuffer@0.1.2 
│ │ │ │ ├── has-binary@0.1.6 
│ │ │ │ └── utf8@2.1.0 
│ │ │ └── ws@1.0.1 
│ │ ├─┬ socket.io-adapter@0.4.0 
│ │ │ └─┬ socket.io-parser@2.2.2 
│ │ │   ├── component-emitter@1.1.2 
│ │ │   ├── debug@0.7.4 
│ │ │   └── json3@3.2.6 
│ │ ├─┬ socket.io-client@1.4.6 
│ │ │ ├── component-emitter@1.2.0 
│ │ │ ├─┬ engine.io-client@1.6.9 
│ │ │ │ ├── component-emitter@1.1.2 
│ │ │ │ ├─┬ engine.io-parser@1.2.4 
│ │ │ │ │ ├── base64-arraybuffer@0.1.2 
│ │ │ │ │ └── has-binary@0.1.6 
│ │ │ │ ├── parsejson@0.0.1 
│ │ │ │ ├── parseqs@0.0.2 
│ │ │ │ ├── ws@1.0.1 
│ │ │ │ └── xmlhttprequest-ssl@1.5.1 
│ │ │ └── parseuri@0.0.4 
│ │ └─┬ socket.io-parser@2.2.6 
│ │   ├── benchmark@1.0.0 
│ │   └── component-emitter@1.1.2 
│ ├─┬ tmp@0.0.28 
│ │ └── os-tmpdir@1.0.2 
│ └─┬ useragent@2.1.9 
│   └── lru-cache@2.2.4 
├─┬ load-grunt-tasks@3.5.2 
│ ├── arrify@1.0.1 
│ ├─┬ multimatch@2.1.0 
│ │ ├── array-differ@1.0.0 
│ │ └─┬ array-union@1.0.2 
│ │   └── array-uniq@1.0.3 
│ ├─┬ pkg-up@1.0.0 
│ │ └─┬ find-up@1.1.2 
│ │   └── path-exists@2.1.0 
│ └─┬ resolve-pkg@0.1.0 
│   └── resolve-from@2.0.0 
├─┬ markdown-it@8.2.1 
│ ├─┬ argparse@1.0.9 
│ │ └── sprintf-js@1.0.3 
│ ├── linkify-it@2.0.2 
│ ├── mdurl@1.0.1 
│ └── uc.micro@1.0.3 
├─┬ shelljs@0.7.5 
│ ├── interpret@1.0.1 
│ └─┬ rechoir@0.6.2 
│   └── resolve@1.1.7 
└─┬ time-grunt@1.4.0 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.0.0 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ date-time@1.1.0 
  │ └── time-zone@0.1.0 
  ├── figures@1.7.0 
  ├── hooker@0.2.3 
  ├── number-is-nan@1.0.1 
  ├─┬ pretty-ms@2.1.0 
  │ ├── is-finite@1.0.2 
  │ ├── parse-ms@1.0.1 
  │ └── plur@1.0.0 
  └── text-table@0.2.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN load-grunt-tasks@3.5.2 requires a peer of grunt@>=0.4.0 but none was installed.

-----------------------------------------------------------------------------------------------------------

[jchailloux@jchaillouxserver READ.develop]$ meteor npm install --save ace yamlparser coffee-script LiveScript ts-node fsevents
npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
npm ERR! argv "/home/jchailloux/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/jchailloux/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install" "--save" "ace" "yamlparser" "coffee-script" "LiveScript" "ts-node" "fsevents"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:

**Comment by sriumcp** [comment]
Did you do `meteor npm install` before doing `meteor`? Its working ok for me.

Please try the following suggestions and see if they work for you.

1. `cd READ.develop`
2. `rm -rf node_modules`
3. `meteor npm install`
4. `meteor`

If the above steps fail, please try a fresh install.

**Comment by sriumcp** [comment]
So is this resolved?

**Comment by jchailloux** [comment]
starting from scratch solved the issue. I still don't know what happened (only suspend on my W530 plus reboot)
