### ISSUE TITLE
Enable to start

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.visualization#155]
After a fresh install

Error: [$injector:modulerr] Failed to instantiate module read due to:
[$injector:nomod] Module 'read' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.9/$injector/nomod?p0=read
minErr/<@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:17279:12
module/<@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:19338:1
ensure@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:19262:38
module@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:19336:1
loadModules/<@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:21871:22
forEach@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:17536:11
loadModules@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:21855:5
createInjector@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:21777:19
bootstrap/doBootstrap@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:19014:20
bootstrap@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:19035:1
angularInit@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:18920:5
require<.node_modules.angular["angular.js"]/</<@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:49590:5
require<.node_modules.jquery.dist["jquery.js"]/</<.Deferred/promise.then/resolve/</mightThrow@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:177208:21
require<.node_modules.jquery.dist["jquery.js"]/</<.Deferred/promise.then/resolve/</process<@http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5:177276:12

http://errors.angularjs.org/1.5.9/$injector/modulerr?p0=read&p1=%5B%24injector%3Anomod%5D%20Module%20'read'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.9%2F%24injector%2Fnomod%3Fp0%3Dread%0AminErr%2F%3C%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A17279%3A12%0Amodule%2F%3C%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A19338%3A1%0Aensure%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A19262%3A38%0Amodule%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A19336%3A1%0AloadModules%2F%3C%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A21871%3A22%0AforEach%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A17536%3A11%0AloadModules%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A21855%3A5%0AcreateInjector%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A21777%3A19%0Abootstrap%2FdoBootstrap%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A19014%3A20%0Abootstrap%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A19035%3A1%0AangularInit%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A18920%3A5%0Arequire%3C.node_modules.angular%5B%22angular.js%22%5D%2F%3C%2F%3C%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A49590%3A5%0Arequire%3C.node_modules.jquery.dist%5B%22jquery.js%22%5D%2F%3C%2F%3C.Deferred%2Fpromise.then%2Fresolve%2F%3C%2FmightThrow%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A177208%3A21%0Arequire%3C.node_modules.jquery.dist%5B%22jquery.js%22%5D%2F%3C%2F%3C.Deferred%2Fpromise.then%2Fresolve%2F%3C%2Fprocess%3C%40http%3A%2F%2F192.168.10.150%3A3000%2Fpackages%2Fmodules.js%3Fhash%3D73e17269a4637c0890f3a88559d81dca26490df5%3A177276%3A12%0A
http://192.168.10.150:3000/packages/modules.js?hash=73e17269a4637c0890f3a88559d81dca26490df5
Line 17279

**Comment by sriumcp** [comment]
Updated READ due to various changes in angular 1.6 and tested that both the developer and sharing UI are working. Please update your meteor (`meteor update`), and reinstall READ as per the usual getting started instructions in order to use this version.
